nome=input("Digite um funcionário:")
empresa=input("DIgite o nome da empresa:")
qtde_defuncionarios=int(input("DIgite a quantidade de funcionários:"))
mediaMensalidade=float(input("Digite a média da mensalidade:"))
print(nome,"trabalha na", empresa)
print("Na empresa do mesmo, trabalham", qtde_defuncionarios, "com a media da mensalidade de", mediaMensalidade, "reais")